#!/usr/bin/env bash

IgnorePath '**.pacnew'

IgnorePath '/.snapshots/*'
IgnorePath '/zfs/*'
IgnorePath '/boot/*'

IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/zfs/*'
IgnorePath '/etc/systemd/system/zfs-*'
IgnorePath '/etc/X11/*'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/pulse/*'
IgnorePath '/etc/NX/*'
IgnorePath '/etc/vmware/*'
IgnorePath '/etc/NetworkManager/system-connections/*'
IgnorePath '/etc/docker/*'
IgnorePath '/etc/libvirt/nwfilter/*'
IgnorePath '/etc/lvm/*'
IgnorePath '/etc/xdg/*'
IgnorePath '/etc/ssh/ssh_host_*'
IgnorePath '/usr/NX/*'
IgnorePath '/usr/LICENSE'
IgnorePath '/etc/zcasos-info'

IgnorePath '/etc/systemd/system/hibernate.target'
IgnorePath '/etc/systemd/system/suspend.target'

IgnorePath '/etc/systemd/system/sponsorblockcast.service.d'
IgnorePath '/etc/systemd/system/sponsorblockcast.service.d/*'
IgnorePath '/etc/systemd/system/\\x2esnapshots.mount.wants'
IgnorePath '/etc/systemd/system/\\x2esnapshots.mount.wants/grub-btrfs.path'

IgnorePath '/opt/*'
IgnorePath '/usr/local/*'
IgnorePath '/var/*'
IgnorePath '/var/tmp/*'
IgnorePath '/var/lib/*'
IgnorePath '/var/log/*'
IgnorePath '/var/cache/*'
IgnorePath '/usr/lib/modules/*'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/usr/share/*'
IgnorePath '/usr/lib/*'
IgnorePath '/usr/lib32/*'
