
SetFileProperty /etc/bluetooth mode 755
SetFileProperty /etc/multipath mode 700
SetFileProperty /etc/pacman.d/gnupg/crls.d mode 700
SetFileProperty /etc/pacman.d/gnupg/openpgp-revocs.d mode 700
SetFileProperty /etc/pacman.d/gnupg/private-keys-v1.d mode 700
SetFileProperty /etc/sssd/conf.d group sssd
SetFileProperty /etc/sssd/pki group sssd
SetFileProperty /etc/sssd group sssd
SetFileProperty /etc/subgid deleted y
SetFileProperty /etc/subuid deleted y
SetFileProperty /etc/sudoers.d mode 755
SetFileProperty /etc/texmf/dvipdfmx/dvipdfmx.cfg deleted y
SetFileProperty /etc/texmf/dvipdfmx deleted y
SetFileProperty /etc/texmf/dvips/config/config.ps deleted y
SetFileProperty /etc/texmf/dvips/config deleted y
SetFileProperty /etc/texmf/dvips deleted y
SetFileProperty /etc/texmf/tex/generic/config/language.dat.lua deleted y
SetFileProperty /etc/texmf/tex/generic/config/language.dat deleted y
SetFileProperty /etc/texmf/tex/generic/config/language.def deleted y
SetFileProperty /etc/texmf/tex/generic/config deleted y
SetFileProperty /etc/texmf/tex/generic/tex-ini-files/pdftexconfig.tex deleted y
SetFileProperty /etc/texmf/tex/generic/tex-ini-files deleted y
SetFileProperty /etc/texmf/tex/generic deleted y
SetFileProperty /etc/texmf/tex deleted y
SetFileProperty /etc/texmf/web2c/fmtutil.cnf deleted y
SetFileProperty /etc/texmf/web2c/mktex.cnf deleted y
SetFileProperty /etc/texmf/web2c/texmf.cnf deleted y
SetFileProperty /etc/texmf/web2c/updmap-hdr.cfg deleted y
SetFileProperty /etc/texmf/web2c deleted y
SetFileProperty /etc/texmf/xdvi/XDvi deleted y
SetFileProperty /etc/texmf/xdvi deleted y
SetFileProperty /etc/texmf deleted y
SetFileProperty /etc/udev/rules.d mode 755
