# Pure
#export PURE_PROMPT_SYMBOL=Δ
export PURE_PROMPT_SYMBOL="λ »"
# Spaceship
export SPACESHIP_VI_MODE_SHOW=false

typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION="$PURE_PROMPT_SYMBOL"
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION="$PURE_PROMPT_SYMBOL"
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION="$PURE_PROMPT_SYMBOL"



