# "Disable" HIDPI
export WINIT_HIDPI_FACTOR=1
export WINIT_X11_SCALE_FACTOR=1

# HIDPI SUX
export QT_FONT_DPI=96
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=1
export QT_SCREEN_SCALE_FACTORS=1
#export GDK_SCALE=2 
#export GDK_DPI_SCALE=-1 
#export XCURSOR_SIZE=48 
